exercises = [
				{name: 'Seated Dumbbell Shoulder Press', targetMuscles: ['right front deltoid', 'left front deltoid', 'lateral deltoids']},
				{name: 'Dumbbell Shoulder Press', targetMuscles: ['right front deltoid', 'left front deltoid', 'lateral deltoids']},
				{name: 'Barbell Bench Press', targetMuscles: ['right pec', 'left pec', 'right front deltoid', 'left front deltoid']},
				{name: 'Bench Press', targetMuscles: ['right pec', 'left pec', 'right front deltoid', 'left front deltoid']},	 	    
				{name: 'Barbell Squat', targetMuscles: ['right glute', 'left glute', 'left quadricep', 'right quadricep']},
				{name: 'Squat', targetMuscles: ['right glute', 'left glute', 'left quadricep', 'right quadricep']},
				{name: 'Conventional Deadlift', targetMuscles: ['right glute', 'left glute', 'left hamstring', 'right hamstring']},
				{name: 'Deadlift', targetMuscles: ['right glute', 'left glute', 'left hamstring', 'right hamstring']},
				{name: 'Wide Grip Pull-ups', targetMuscles: ['right lat', 'left lat', 'biceps']},
				{name: 'Front Squat', targetMuscles: ['left quadricep', 'right quadricep']},
				{name: 'Hammer Curl', targetMuscles: ['left forearm', 'right forearm']},
				{name: 'Tricep Pushdown', targetMuscles: ['left tricep', 'right tricep']},
				{name: 'Push-Ups', targetMuscles: ['right pec', 'left pec', 'left tricep', 'right tricep']},
				{name: 'Sit-Ups', targetMuscles: ['abdominals']},
				{name: 'Hip Thrust', targetMuscles: ['right glute', 'left glute', 'left hamstring', 'right hamstring']},
				{name: 'Leg Extension', targetMuscles: ['left quadricep', 'right quadricep']},
				{name: 'Standing Calf Raises', targetMuscles: ['right calf', 'left calf']},
				{name: 'Standing Overhead Press', targetMuscles: ['left front deltoid', 'right front deltoid']},
				{name: 'Lat Pulldown', targetMuscles: ['right lat', 'left lat', 'left bicep', 'right bicep']},
				{name: 'Barbell Row', targetMuscles: ['lower back', 'upper traps', 'mid-lower traps', 'right lat', 'left lat']},
				{name: 'Dumbbell Lateral Raise', targetMuscles: ['right rear deltoid', 'left rear deltoid']},
				{name: 'Leg Press', targetMuscles: ['left quadricep', 'right quadricep', 'left hamstring', 'right hamstring']},
				{name: 'Barbell Curl', targetMuscles: ['left bicep', 'right bicep']},
				{name: 'Incline Dumbbell Press', targetMuscles: ['right pec', 'left pec']},
				{name: 'Lying Leg Curl', targetMuscles: ['left hamstring', 'right hamstring']},
				{name: 'Romanian Deadlift', targetMuscles: ['right glute', 'left glute', 'left hamstring', 'right hamstring']},
				{name: 'Dumbbell Row', targetMuscles: ['right lat', 'left lat', 'mid-lower traps', 'left bicep', 'right bicep']},
				{name: 'Face Pull', targetMuscles: ['left tricep', 'right tricep', 'upper traps']},
				{name: 'Cable Close Grip Seated Row', targetMuscles: ['right lat', 'left lat']},
				{name: 'Pull-Ups', targetMuscles: ['left lat', 'right lat', 'left bicep', 'right bicep']},
				{name: 'Bulgarian Split Squat', targetMuscles: ['right glute', 'left glute', 'left quadricep', 'right quadricep']},
				{name: 'Cable Chest Fly', targetMuscles: ['right pec', 'left pec']},
				{name: 'Military Press', targetMuscles: ['right front deltoid', 'left front deltoid']},
				{name: 'Skull Crushers', targetMuscles: ['left tricep, right tricep']},
				{name: 'Bicep Curl', targetMuscles: ['left bicep, right bicep']},
				{name: 'Dumbbell Tricep Extension', targetMuscles: ['left tricep, right tricep']},
				{name: 'Chin-Up', targetMuscles: ['left lat', 'right lat', 'left bicep', 'right bicep']},
				{name: 'Seated Cable Row', targetMuscles: ['left lat', 'right lat', 'left bicep', 'right bicep']},
				{name: 'Preacher Curl', targetMuscles: ['left bicep', 'right bicep']},
				{name: 'Cable Flyes', targetMuscles: ['left pec', 'right pec']},
				{name: 'Close Grip Bench Press', targetMuscles: ['left pec', 'right pec']},
				{name: 'Dips', targetMuscles: ['left pec', 'right pec']},
				{name: 'Chest Flyes', targetMuscles: ['right pec', 'left pec']},
				{name: 'Overhead Tricep Extension', targetMuscles: ['left tricep', 'right tricep']},
				{name: 'Tricep Dips', targetMuscles: ['left tricep', 'right tricep']},
			]
module.exports = exercises
